### ISSUE TITLE
Unknown parameter version! at ./qrcode_with_jwt.pl line 34.

### ISSUE THREAD

**Issue by ghenry** [Tekki/svg-barcode-qrcode#1]
Hi,

I was looking for an SVG distro last night and found your new one. I get an error with your example:

```
use strict;
use warnings;

use SVG::Barcode::QRCode;
 
my %params = (
  background => 'white',
  foreground => 'black',
  level      => 'M',
  margin     => 10,
  size       => 5,
  version    => 0,
);
my $qrcode = SVG::Barcode::QRCode->new(\%params);
my $svg    = $qrcode->plot('https://perldoc.pl');
my $svg2   = $qrcode->param(foreground => 'red')->plot('https://perldoc.pl');
```

error:

`Unknown parameter version! at ./qrcode_with_jwt.pl line 34.`

is there a version in your parent?

**Comment by Tekki** [comment]
> is there a version in your parent?

Hi Gavin, thanks for reporting this issue.
`version` comes from QRCode itself. Seems to be a zero/undef error in SVG::Barcode. :see_no_evil:
I'll fix it until tomorrow.

**Comment by Tekki** [comment]
@ghenry breaking changes arriving with version 0.10!
